### ISSUE TITLE
Installing on Linux

### ISSUE THREAD

**Issue by weaverbel** [stencila/desktop#11]
Can you please supply instructions for downloading and installing the latest desktop on Linux? Do I install the tar.gz and then the desktop? Or if it is just the desktop AppImage file, then what do I use to install it? My laptop is suggesting ParPy? Not sure what kind of package it is so I can't tell.

**Comment by nokome** [comment]
Thanks @weaverbel for trying it out!

You should be able to install on all major linux distributions just by downloading and double clicking on the AppImage file. You shouldn't need to instal any other dependencies first. See http://appimage.org/ for more on the AppImage format.

When I do the above on Ubuntu Xenial get this dialog and it installs when I click "Make executable and run":

![image](https://cloud.githubusercontent.com/assets/1152336/25619785/f5a80a9e-2f00-11e7-8668-51155ef1940d.png)

Regardless, I'll setup a "Download" page with instructions

**Comment by nokome** [comment]
@weaverbel : I've added a Wiki page on our main repo with instructions for installs https://github.com/stencila/stencila/wiki - see what you think of them

@michael : I've added some Mac instructions I found on the web to that wiki - could you edit them (more concise?)

@oliver---- : would you you be able to add instructions for windows (and the binary to releases page, please :+1: )

**Comment by weaverbel** [comment]
Thanks @nokome I get an error and it searches for an app. It offers me some python tools. Will check out the wiki.

**Comment by weaverbel** [comment]
And now I am good !!! Thanks @nokome

**Comment by nokome** [comment]
Closing this, as it now seems to be resolved.
