### ISSUE TITLE
Sign Windows builds

### ISSUE THREAD

**Issue by nokome** [stencila/desktop#24]
Windows builds should be signed. Without signing, users get an installation warning "The publisher could not be verfied". 

Also, unsigned builds may be lead anti-virus programs to quarantine the app (e.g McAffee LiveSafe as reported [here](https://twitter.com/Syenta1/status/911343154971987968)) VirusTotal [does not detect any issues with the 0.27.4 Windows build](https://www.virustotal.com/#/file/79333f064385338632d72405096abbcbf52fa208c3fd07632e696c2d50925f7e/detection) so a lack of code signing is likely to be to blame.

This is equivalent to issue #18 which is for signing Mac builds. See https://www.electron.build/code-signing for instructions on setting up both.

**Comment by kantrowitz** [comment]
Yes, Symantec quarantines it, as of today 2/5/2018, using Stencila.Setup.0.27.4, and Windows 7. Where is 0.28.4 released from?

**Comment by nokome** [comment]
Thanks for the feedback. Sorry for the hassle.

> Where is 0.28.4 released from?

That was a typo in my comment. Should have said  "0.27.4 Windows build" - have fixed it.

We won't be doing another release until a 1.0.0-beta - targeted for March. We will certainly aim to have signed builds for that.
