### ISSUE TITLE
Save triggers Save as

### ISSUE THREAD

**Issue by apawlik** [stencila/desktop#34]
When trying to save document from the menu or by `Ctrl+S` shortcut, Desktop opens `Save as` dialog window.

![save_bug](https://user-images.githubusercontent.com/2358535/39411734-58c75158-4c64-11e8-8073-40d460d01aef.gif)

**Comment by nokome** [comment]
I had the same issue, also on Linux. It seems to occur only when try to save the blank project that pops up at startup, not on `New` projects, or `Open`ing existing projects.

**Comment by apawlik** [comment]
Yeah. I will be trying out on Windows as well to see what happens.

**Comment by nokome** [comment]
Closing as I believe it is fixed by #51
