### ISSUE TITLE
Automatically add rows/columns when copy-pasting cells from different spreadsheet 

### ISSUE THREAD

**Issue by apawlik** [stencila/desktop#35]
A newly opened Stencila Sheet has 10 rows and 21 columns. When copy-pasting more than 10 rows / 21 columns from another spreadsheet application, the data gets truncated to these 10 rows / 21 columns. A user will expect the data to be all copied and Stencila Sheet to automatically add more rows columns. 
 
Temporary solution could adding at least a warning ("Only 10 first rows / 21 columns will be copied").

**Comment by oliver----** [comment]
Thanks! Will work on that.

**Comment by oliver----** [comment]
This ready as a PR in stencila: https://github.com/stencila/stencila/pull/651

**Comment by nokome** [comment]
FIxed
