### ISSUE TITLE
Can't switch back to article tab after copy-pasting cells to sheet

### ISSUE THREAD

**Issue by apawlik** [stencila/desktop#36]
After copy-pasting data (cells) from another spreadsheet programme (Libre Office), can't switch back to the article tab. 
Also the click brings up the submenu (`Remove`).

![cnt_swicth_tabs](https://user-images.githubusercontent.com/2358535/39412274-f952aace-4c6d-11e8-952e-f63624e323eb.gif)

**Comment by oliver----** [comment]
Taking this one.

**Comment by oliver----** [comment]
@apawlik I am trying to reproduce this. No luck so far.
Need your help to narrow this down.
Is this happening with a blank document too, or is it a specific document?

**Comment by apawlik** [comment]
@oliver---- 
I started with a blank document. Will try reopening an existing one and see if that happens.

**Comment by apawlik** [comment]
@oliver----  Can't reproduce now myself :-( Sorry. I also overwrote the document which I used for the GIF above when catching the ['Save as" issue](https://github.com/stencila/desktop/issues/34).

Closing for now (?)

**Comment by oliver----** [comment]
No worries.
This might happen if there is another bug elsewhere and the app got stuck due to an exception.
In these cases you might want to open the developer console and take a screenshot of the console output. This might help us to lead us to the underlying problem.

Thanks for the help!

**Comment by apawlik** [comment]
Mhaa! Forgot about the console. Thanks!
