### ISSUE TITLE
`Reload` should warn that `unsaved changes will be lost` and it will `open a new document`

### ISSUE THREAD

**Issue by apawlik** [stencila/desktop#38]
`Reload` re-opens with a clean new Stencila document not giving any warning about it. Any unsaved changes are lost.

The word `Reload` can also be confusing. The user may expect that it will just refresh the document / restart connections to execution contexts etc. Maybe `Reset` would be better?

**Comment by michael** [comment]
I removed the menu items for reload/force reload altogether. So this should be addressed once the next PR is merged.
