### ISSUE TITLE
Disable using duplicate names for sheets (and articles?)

### ISSUE THREAD

**Issue by apawlik** [stencila/desktop#42]
At the moment Stencila allows for duplicate names for Sheets and Articles (i.e. there may be multiple sheets with the same name). This may lead to problems when referencing sheets (connecting with data). Also other spreadsheet applications don't allow for duplicates so we should be consistent.

**Comment by oliver----** [comment]
I agree.

Will take care of this.

**Comment by oliver----** [comment]
We will disallow duplicate names in the editor similar to Google Sheets does it.
If we find a duplicate document during import (whysoever this might happen), we gonna change the name on-the-fly by adding a `... (2)`.

**Comment by apawlik** [comment]
Maybe add an explicit word (duplicate)?

**Comment by oliver----** [comment]
Good idea!
