### ISSUE TITLE
Disable special characters in sheet / article names?

### ISSUE THREAD

**Issue by apawlik** [stencila/desktop#43]
We should probably consider how allowing for special characters in sheet and article naming may impact referencing them. 
Google Spreadsheets seems to allow special characters such as [ ] * /
However, Libre Office and Excel don't allow  [ ] * ? : / \
 
How should we go about this one?

**Comment by oliver----** [comment]
I'd opt for keeping the names simple for now, i.e. disallow them.

**Comment by apawlik** [comment]
Yes, I agree. I'd even restrict (for now) it to English alphabet, I.e. not allowing for characters with diacritics (ę, ą, ü and so on).
