### ISSUE TITLE
Blank document still open after opening existing DAR

### ISSUE THREAD

**Issue by apawlik** [stencila/desktop#45]
Possibly confusing for users but not critical.
If a user goes straight into opening an existing DAR from newly launched Stencila Desktop, a blank document is still open (which opens by default when launching Stencila). This may be confusing for users as most software does not have the blank file (document, spreadsheet etc) still available after a user opened an existing file.
(Hope I managed to explain what I meant)

**Comment by michael** [comment]
What I’d like to do is on app start show a file open prompt, but in the same dialog a “New Document” button. Apps like Sketch do it like that.

**Comment by apawlik** [comment]
@Michael that's a neat idea
