### ISSUE TITLE
Linux build fails opening existing DAR

### ISSUE THREAD

**Issue by apawlik** [stencila/desktop#54]
Brand new build on Ubuntu 16.04 of Desktop 0.28

1) Trying to open https://github.com/stencila/stencila/tree/develop/examples/kitchen-sink or https://github.com/stencila/stencila/tree/develop/examples/mini gives
`ERROR:Could not find <dar> element.`

2) Trying to open a `dar` created from a simple Markdown (eg. https://github.com/stencila/examples/tree/master/mtcars/mtcars.dar) using `stencila convert` gives:
`ERROR:Cannot read property 'hasPendingChanges' of undefined`

3) Trying to open https://github.com/stencila/examples/tree/master/intermine/tutorials.dar gives
`ERROR:Cannot read property 'rest' of undefined`

**Comment by nokome** [comment]
> I had a gut feeling that renaming these files is a big mistake ;-)

Not your fault! It's the fault of the damn cowboy developer who wrote that crap converter package. :roll_eyes: 

WRT to 3 I get the same error (below, note also has the `hasPendingChanges` error) but if I do a `Ctrl+R` to reload it works. I have noticed these errors several times before, they seem to be related to the wrong order of sync events at startup (???)

![image](https://user-images.githubusercontent.com/1152336/40219180-6f3fb200-5ac8-11e8-92f0-21b389f6baa6.png)

**Comment by nokome** [comment]
WRT to 1: I don't get any errors on either of those files and the error `ERROR:Could not find <dar> element.` is surprising since the `manifest.xml` in both of those folders has a `<dar>` element e.g. https://github.com/stencila/stencila/blob/develop/examples/kitchen-sink/manifest.xml Can you check the manifest file locally?

**Comment by oliver----** [comment]
Short stats report:
- a missing `<dar>` element indicates a corrupt `manifest.xml`
- the `hasPendingChanges` error is tracked here: https://github.com/substance/texture/issues/531
- the `rest` error should be solved partly via https://github.com/stencila/stencila/pull/702
  There seems to be a wrong language identifier somewhere. But we should see this now via an error 
  message on the console.
