### ISSUE TITLE
Use asarUnpack to unpack files e.g. blank docs

### ISSUE THREAD

**Issue by nokome** [stencila/desktop#56]
Using asar was causing issues (e.g. #50) but now we are diabling it, `electron-builder` is warning us that "asar using is disabled — it is strongly not recommended solution=enable asar and use asarUnpack to unpack files that must be externally available". 

This hints at the problem perhaps, the embedded DAR server was unable to access the files when using asar. Using `asarUnpack`, whatever that is, may remedy that.

**Comment by will0225** [comment]
I am getting same error now
