### ISSUE TITLE
Can't open large Stencila Sheets

### ISSUE THREAD

**Issue by apawlik** [stencila/desktop#57]
A [converted example](https://github.com/stencila/examples/blob/master/diamonds/diamonds.dar/data.csv.sheet.xml) includes a large (>13MB,  >5K records) sheet (converted from plain csv). Opening the dar in Desktop results in blank Desktop screen and no feedback. It's still possible to close the Desktop window but it should:
* display a message "file too large" OR  
* (in case it actually can open a Sheet of that size) display a message "please wait"

**Comment by oliver----** [comment]
Thanks @apawlik!

This is definitely something I want to improve. There are already measures for this, but it seems that they are ineffective or insufficient. 
Now I have an example 😄 Will investigate.
