### ISSUE TITLE
Linux desktop appImage fails to run in Fedora 27, 64_bit

### ISSUE THREAD

**Issue by Andyroo1966** [stencila/desktop#66]
Hello, just trying to launch the appImage for the Linux Desktop app under Fedora 27 64bit. Unfortunately, after initially popping up a window to ask for setting up to work alongside the desktop, the app core dumped. Now if I try and run it again, it immediately coredumps...
The initial error was a Javascript error
Tried via sudo - same sequence as when launched as a normal user. Window popped up, I selected yes, it crashed.

Interestingly, I have 5 seperated .mount_stenci..... files in /tmp which I do not have permission to read as sudo! And a .mount_stenciJDVlVp directory. I can't delete any of them in this current desktop session. I will reboot and see if that unlocks anything.
Files gone from /tmp on reboot. But appImage launch still fails immediately. Output from ls -al /tmp/.mount_stencip7zyQw/
ls: /tmp/.mount_stencip7zyQw/: Transport endpoint is not connected

**Comment by almereyda** [comment]
Same error on Fedora 29 here, immediate segmentation fault after running the AppImage.

**Comment by hmontenegro** [comment]
> Same error on Fedora 29 here, immediate segmentation fault after running the AppImage.

Same on Debian testing, either downloading the latest stencila-desktop-0.28.2x86_64.AppImage release, or building from scratch.
