### ISSUE TITLE
Two (unsaved) documents share the same Python kernel 

### ISSUE THREAD

**Issue by rgaiacs** [stencila/desktop#67]
The variables from one unsaved document is accessible from another unsaved document. This creates problems when creating visualisations with matplotlib.

# Current Behaviour

Variable created in document `X` is accessible in document `Y`. **Both documents weren't save.**

# Expected Behaviour

Variable created in document `X` is **only** accessible in document`X`.

# How to reproduce

1. Open Stencila.
2. Create one reproducible picture with matplotlib
3. Create a new document.
4. Create another reproducible picture with matplotlib

![screenshot from 2018-07-26 23-58-13](https://user-images.githubusercontent.com/1506457/43292993-e8e7bf56-912f-11e8-93a0-793addb252ec.png)

**Comment by nokome** [comment]
@rgaiacs thanks for taking the time to make the detailed bug report! The two documents have different execution contexts (i.e. kernel) within the same process. I don't think the variable is shared between the two contexts (that is a :bug: if it is!). Instead, I think this is related to multiple rendering on to matplotlib's global graphics device.

I will move this over to the `stencila/py` repo where is better belongs.

**Comment by nokome** [comment]
Replaced by https://github.com/stencila/py/issues/20
