### ISSUE TITLE
References not saved/incompletely saved on MacOsX

### ISSUE THREAD

**Issue by lollopus** [stencila/desktop#68]
References are saved erratically. Sometimes they are not saved at all (I have a manuscript being edited that I can send you for testing that replicates this).

With newly created empty files, references with only their title field filled out are saved but said title is missing when reopening the file. In one instance when reopening the file I got the following error:

```
    Importing JATS
    Parse XML
    Validate JATS
    <element-citation> is incomplete. Schema: (inline-supplementary-material|related-article|related-object|hr|string-date|bold|fixed-case|italic|monospace|overline|overline-start|overline-end|roman|sans-serif|sc|strike|underline|underline-start|underline-end|ruby|alternatives|inline-graphic|private-char|chem-struct|inline-formula|label|tex-math|mml:math|abbrev|milestone-end|milestone-start|named-content|styled-content|annotation|article-title|chapter-title|collab|collab-alternatives|comment|conf-acronym|conf-date|conf-loc|conf-name|conf-sponsor|data-title|date|date-in-citation|day|edition|email|elocation-id|etal|ext-link|fpage|gov|institution|institution-wrap|isbn|issn|issn-l|issue|issue-id|issue-part|issue-title|lpage|month|name|name-alternatives|object-id|page-range|part-title|patent|person-group|pub-id|publisher-loc|publisher-name|role|season|series|size|source|std|string-name|supplement|trans-source|trans-title|uri|version|volume|volume-id|volume-series|year|fn|target|xref|sub|sup|x)+
    <element-citation publication-type="data">
    </element-citation>
    Transform JATS -> TextureArticle
    Validate Dar Article
    Transform TextureArticle -> InternalArticle
    Validate Texture Article
```

Essentially saving behavior is erratic. Unless I'm doing something wrong I deem this issue as **blocking/very high priority** since it makes using stencila on real manuscript drafting impossibile!

**Comment by nokome** [comment]
@lollopus : thanks for taking the time to submit this bug report, and the duplicate in Texture. Is it OK with you if we close this one in favour of the Texture one (which is the right place for it)?

**Comment by lollopus** [comment]
No problem, @michael said they will address this issue in the September release... cheers
