### ISSUE TITLE
Open links using electron.shell.openExternal

### ISSUE THREAD

**Issue by rgbkrk** [stencila/desktop#8]
Sweet to try out Stencila desktop!

For all the links in the document, you should make sure to use [`shell.openExternal`](https://github.com/electron/electron/blob/master/docs/api/shell.md#shellopenexternalurl-options-callback) for all external links. It's either that or ensuring the window being opened doesn't have node access. Check the console on the link to gitter in the welcome notebook -- you and, by extension gitter, have access to the user's computer _remotely_.

Within nteract we setup a listener on the `will-navigate` event: https://github.com/nteract/nteract/blob/6383c940f38017088ff3612c2ff3f2d072055983/src/main/launch.js#L46

**Comment by nokome** [comment]
Mmmm, thanks a lot for pointing that out @rgbkrk !

We should probably fix this and make a patch release ASAP. @michael let me know if you can address this before your flight home. If not, I can do it.

**Comment by michael** [comment]
Hey, yeah we should do a patch release. But maybe get few more fixes in. Like the plots that are not updating. Go ahead with fixing small things you, but i would say we aim for next week for a proper patch release?

**Comment by nokome** [comment]
Yep, putting more into a patch release next week makes more sense :+1:

**Comment by michael** [comment]
@rgbkrk I can't find a way to intercept when a new window is opened via `window.open(..., '_blank')`. The `new-window` event fires but too late (event.preventDefault does not have an effect). So while I'm able to call shell.openExternal, I can't prevent the internal window from opening and end up with two open windows. Do you have an idea how this could be solved? Thank you for help!

**Comment by rgbkrk** [comment]
Hmmm I don't think we've overridden that before. It looks like you can pass BrowserWindow options at least to the initial `window.open` call -- https://github.com/electron/electron/blob/master/docs/api/window-open.md

Perhaps it would be good to override `window.open` to cause it to use `electron.shell.openExternal`. You could do this before anything else is loaded on the page.

```
const originalOpen = window.open

window.open = function(url, frameName, features) {
  electron.shell.openExternal(url);
}
```

**Comment by michael** [comment]
Hey thanks. That's a bit of a hack, but does the job for now. 👍

The problem is really, that I don't want the desktop app to dictate how some components deal with links (no electron-specific code should be in the editor's link component for instance). So I guess my approach would be to open everything external unless explicitly marked 'internal'.
